# Generated by Django 3.2.8 on 2021-10-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type_id', models.CharField(max_length=255)),
                ('food_image_url', models.URLField(blank=True, max_length=255)),
                ('approve_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='UserPostLikes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_like', models.BooleanField(default=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurant'),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(related_name='tagged_users', to='authentication.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
