# Generated by Django 3.2.8 on 2021-10-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211013_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('food_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserPostLikes',
            new_name='UserPostLike',
        ),
    ]
