# Generated by Django 3.2.8 on 2021-10-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211013_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.foodtype'),
        ),
    ]
