# Generated by Django 3.2.8 on 2021-10-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_post_food_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_users',
        ),
    ]
