# Generated by Django 3.2.8 on 2021-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_post_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
