# Generated by Django 3.2.8 on 2021-10-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_post_food_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreemiumUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('quota_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
