# Generated by Django 3.2.7 on 2021-10-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20211014_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='food_type_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userpostlike',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='userpostlike',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='UserPostLike',
        ),
    ]
