# Generated by Django 3.2.7 on 2021-10-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_username_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo_url',
            field=models.URLField(blank=True),
        ),
    ]
