# Generated by Django 3.2.7 on 2021-10-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_pass_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
